### ISSUE TITLE
Extract the username from the repo address 

### ISSUE THREAD

**Issue by freshteapot** [varnish/varnishgather#27]
I would like to have where possible the username from the repos url, so we can see in the gather how the machine links to the customer.

I feel we must filter out the password.

Via apt or yum

structure in apt source file:
```
deb https://USER:PASSWORD@repo.varnish-software.com/ubuntu trusty non-free
```

structure in yum source file:
```
baseurl=https://USER:PASSWORD@repo.varnish-cache.org/redhat/varnish/el$releasever
```

## apt
```
/etc/apt/sources.list.d/varnish-XXXX.list
```

## yum
```
/etc/yum/sources.list.d/varnish-XXXX.list
```

**Comment by huayra** [comment]
Do not really see the point with that as we have the repository logs anyway.

But if you get it, we can cross-match that information.

What is the goal with this information?

**Comment by Dridi** [comment]
This is also not very reliable, some users may use a (Red Hat) Satellite or something similar to avoid having production machines getting packages directly from the Internet.

**Comment by freshteapot** [comment]
@Dridi unreliable is fine, then we don't get a username. I still feel for those that do it is invaluable.

@huayra you don't need to get it ;). The cross-match of information is part of the reason behind it.

The goal of this information, and other information from the gather is to help populate our future knowledge base of what our customers are using.

The gather is a great source of analytics of what things users are using within the varnish world.

- vmods
- version of varnish
- using varnish plus
- using mse
- etc

**Comment by huayra** [comment]
TBH I think it is more valuable for us whether the software has been downloaded or not by our customers, rather than check whether a certain server links or not. 

The principle is: We trust that our customers follow, in good faith, the provisions in the contract they have with us.

I find the shortname to be quite useful as it is immutable across all our internal systems and it is the variable I use to create the Varnish Plus software usage overview sales uses to understand what their respective accounts are consuming, and most importantly, what they are not:

- [Overview per customer/product](https://docs.google.com/spreadsheets/d/16GpLUYACdydigwdS-46QCEw-1IHpo0jC7Ovza5A58Dg/edit#gid=1815035387)
- [Overview per customer weighted](https://docs.google.com/spreadsheets/d/16GpLUYACdydigwdS-46QCEw-1IHpo0jC7Ovza5A58Dg/edit#gid=128706310)
- [Overview of software in per LOST customer](https://docs.google.com/spreadsheets/d/16GpLUYACdydigwdS-46QCEw-1IHpo0jC7Ovza5A58Dg/edit#gid=55420708)

And more if you review the other sheets in that same document. With help from @denisbr and @mbekkelund I hope to get this into Spiros once https://github.com/varnish/spiros/issues/52 is closed.

**Comment by freshteapot** [comment]
For debian:

```
grep -InHR  'varnish' /etc/apt/
```

Slightly concerned about, possibly sharing the password part.

Another variation is this:

```
grep -InHR  'varnish' /etc/apt/ | awk -F'@' '{print $1}' | awk -F'://' '{print $2}' | cut -d':' -f1
```

Of course, we could try and replace the password with *** or something.

**Comment by rezan** [comment]
We have package info already. Not sure if we need repo login. Please re-open if this is needed.
